### ISSUE TITLE
Results?

### ISSUE THREAD

**Issue by Zireael07** [Donn-Eddy/CS_Performance_Test#1]
Title.

**Comment by Donn-Eddy** [comment]
Sorry for the late reply.
Some raw results can be seen here: https://github.com/Donn-Eddy/CS_Performance_Test/blob/d56259a4ee5d2c068e305f52f6b6f146969cced6/Results/Results.csv

I am saving this under a new branch and starting a Godot 4.0 performance comparison with new tests.
